if(MSVC)
  set(SDL2_PREFIX "E:/Portable/SDL2-2.0.12")
  set(SDL2_LIB "SDL2.lib")
  set(SDL2_LIBDIR "${SDL2_PREFIX}/lib/x64")
  set(SDL2_INCLUDE_DIRS "${SDL2_PREFIX}/include")
  set(SDL2_LIBRARIES
      "-L${SDL2_LIBDIR} -Wl,--enable-new-dtags -lSDL2 ")
  string(STRIP "${SDL2_LIBRARIES}" SDL2_LIBRARIES)
  set(SDL2_FOUND TRUE)
endif(MSVC)
